# site settings
title: Mitos y Drogas
subtitle: Tu guía para reducción de daños
email: mitosydrogas@gmail.com
description: Información crítica y objetiva sobre el uso y la <br />prevención del abuso de substancias.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Gerardo Ortega Alcocer
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555
formspree: xwkkzoqq

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

permalink: drogas/:slug

exclude:
  - elements.md
  - generic.md

# social settings
# 500px_url:
# facebook_url:
# github_url:
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
